version: "3.7"

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - db-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: PASSWORD
      MYSQL_DATABASE: DATABASE

volumes:
  db-mysql-data: