version: "3.7"

services:
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - api

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - db-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: *
      MYSQL_DATABASE: *

volumes:
  db-mysql-data: